services:
  - type: web
    name: ambulance-flask-app
    env: python
    plan: free
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ambulance-db
          property: connectionString

databases:
  - name: ambulance-db
